repository:
  default_branch: main
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY
  delete_branch_on_merge: true

branch_protection:
  main:
    required_pull_request_reviews:
      required_approving_review_count: 1
    required_status_checks:
      contexts:
        - 'PR / Check PR title'
    required_conversation_resolution: true
    required_signatures: true
    required_linear_history: true
